"""
PostgreSQL 上手与 SQLite 迁移 —— hands-on-python 第五系列（数据库）实验 06
核心要点: 容器化 PostgreSQL、psycopg 3 连接管理、跨库迁移对账、
          IDENTITY 主键、JSONB / ARRAY / NUMERIC 三种专有类型

前置: ./pg_migration.sh start 已拉起容器(端口 55432, 库 lab)
生命周期(由 shell 编排, 本脚本只做 demo 一步):
  connect   连 PG, 确认版本, psql 元命令看表清单
  migrate   SQLite 内存库三表 -> PG, 逐表行数对账 + 抽查内容
  types     JSONB / text[] / NUMERIC(10,2) 写入读回精度断言
运行: ../.venv/bin/python pg_migration.py   (由 ./pg_migration.sh 调用)
"""

import json
import os
import sqlite3
import subprocess
import sys
import time
from decimal import Decimal

import psycopg

CONTAINER = "lab06-pg"
PORT = os.environ.get("LAB06_PORT", "55432")
CONNINFO = dict(host="127.0.0.1", port=PORT, dbname="lab",
                user="postgres", password="lab")

PASS_COUNT = 0


def connect_pg(retries=15, delay=1.0):
    """连接 PG: 容器 initdb 阶段的临时实例会让 pg_isready 提前探活成功,
    真实例可能仍在重启, 所以带重试。"""
    last = None
    for _ in range(retries):
        try:
            return psycopg.connect(**CONNINFO)
        except psycopg.OperationalError as err:
            last = err
            time.sleep(delay)
    raise SystemExit(f"PostgreSQL 连不上(已重试 {retries} 次): {last}")


def ok(label, cond, detail=""):
    """断言并把结果打进输出: 通过记 [PASS], 失败抛 AssertionError 中止全流程。"""
    global PASS_COUNT
    if not cond:
        print(f"  [FAIL] {label} {detail}")
        raise AssertionError(label)
    PASS_COUNT += 1
    print(f"  [PASS] {label}")


def step(name, desc):
    print(f"\n=====> [{name}] {desc}")


# ============================================================
# 1. connect — 连接与 psql 元命令
# ============================================================

def do_connect():
    step("connect", f"psycopg 3 连 127.0.0.1:{PORT}/lab, psql 元命令看表清单")
    with connect_pg() as conn, conn.cursor() as cur:
        cur.execute("SELECT version()")
        version = cur.fetchone()[0]
        print("   ", version.split(",")[0])
        ok("PostgreSQL 16 主线版本", version.startswith("PostgreSQL 16"))
    proc = subprocess.run(
        ["docker", "exec", CONTAINER, "psql", "-U", "postgres", "-d", "lab", "-c", "\\dt"],
        capture_output=True, text=True, check=True)
    out = proc.stdout + proc.stderr   # 非交互 psql 把 "Did not find" 写在 stderr
    print("    psql \\dt (迁移前):", out.strip() or "(空)")
    ok("psql 元命令可用且此刻库为空", "Did not find any relations" in out)


# ============================================================
# 2. migrate — SQLite 三表 -> PG, 逐表对账
# ============================================================

def do_migrate():
    step("migrate", "内存 SQLite 三表(实验 02 同款数据)迁入 PG, 逐表行数对账")
    src = sqlite3.connect(":memory:")
    src.executescript("""
        CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
        CREATE TABLE courses (id INTEGER PRIMARY KEY, name TEXT NOT NULL,
                              teacher TEXT NOT NULL);
        CREATE TABLE enrollments (id INTEGER PRIMARY KEY,
                                  student_id INTEGER, course_id INTEGER);
    """)
    src.executemany("INSERT INTO students VALUES (?, ?)",
                    [(1, "张三"), (2, "李四"), (3, "王五"), (4, "赵六")])
    src.executemany("INSERT INTO courses VALUES (?, ?, ?)",
                    [(1, "数学分析", "张教授"), (2, "大学物理", "钱教授"),
                     (3, "线性代数", "孙教授"), (4, "机器学习引论", "周教授")])
    src.executemany("INSERT INTO enrollments VALUES (?, ?, ?)",
                    [(1, 1, 1), (2, 1, 2), (3, 2, 1), (4, 3, 1), (5, 3, 3), (6, 4, 2)])
    src.commit()

    with connect_pg() as conn, conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE students (
                id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL
            );
            CREATE TABLE courses (
                id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name    TEXT NOT NULL,
                teacher TEXT NOT NULL
            );
            CREATE TABLE enrollments (
                id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id INTEGER NOT NULL REFERENCES students(id),
                course_id  INTEGER NOT NULL REFERENCES courses(id)
            );
        """)
        for table, cols in (("students", "id, name"),
                            ("courses", "id, name, teacher"),
                            ("enrollments", "id, student_id, course_id")):
            col_list = cols.split(", ")
            rows = src.execute(f"SELECT {cols} FROM {table}").fetchall()
            cur.executemany(
                f"INSERT INTO {table} ({cols}) VALUES "
                f"({', '.join(['%s'] * len(col_list))})",
                rows)
        conn.commit()

        for table in ("students", "courses", "enrollments"):
            pg_n = cur.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            lite_n = src.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            print(f"    {table}: SQLite {lite_n} 行 -> PG {pg_n} 行")
            ok(f"{table} 行数对账一致 ({lite_n})", pg_n == lite_n)

        cur.execute("""
            SELECT c.teacher, COUNT(e.id) FROM courses c
            LEFT JOIN enrollments e ON e.course_id = c.id
            WHERE c.name = '数学分析' GROUP BY c.teacher""")
        teacher, n = cur.fetchone()
        print(f"    抽查: PG 里'数学分析'授课 = {teacher}, 选课 {n} 条")
        ok("迁移后内容抽查: 张教授 3 条选课", teacher == "张教授" and n == 3)


# ============================================================
# 3. types — JSONB / ARRAY / NUMERIC 精度断言
# ============================================================

def do_types():
    step("types", "三种 SQLite 没有的类型: 写入读回精度无损")
    doc = {"name": "机械键盘", "tags": ["外设", "热插拔"], "specs": {"keys": 87}}
    tags = ["外设", "87 键"]
    price = Decimal("329.99")     # NUMERIC 用十进制精确存, 不走二进制浮点

    with connect_pg() as conn, conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE product_specs (
                id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                attrs  JSONB NOT NULL,
                tags   TEXT[] NOT NULL,
                price  NUMERIC(10, 2) NOT NULL
            );
            CREATE INDEX idx_attrs ON product_specs USING GIN (attrs);
        """)
        cur.execute(
            "INSERT INTO product_specs (attrs, tags, price) VALUES (%s, %s, %s)",
            (psycopg.types.json.Json(doc), tags, price))
        conn.commit()

        cur.execute("SELECT attrs, tags, price FROM product_specs")
        r_doc, r_tags, r_price = cur.fetchone()
        print(f"    JSONB : {r_doc}")
        print(f"    TEXT[]: {r_tags}")
        print(f"    NUMERIC: {r_price} (类型 {type(r_price).__name__})")
        ok("JSONB 写入读回 == 原 dict(嵌套无损)", r_doc == doc)
        ok("text[] 写入读回 == 原 list", r_tags == tags)
        ok(f"NUMERIC 读回 == Decimal({price}) 精确无损",
           r_price == price and isinstance(r_price, Decimal))

        cur.execute("SELECT id FROM product_specs WHERE attrs @> %s::jsonb",
                    (json.dumps({"name": "机械键盘"}),))
        ok("GIN 索引下 JSONB 包含查询 @> 命中 1 行", cur.fetchone() is not None)


# ============================================================
# main
# ============================================================

def main():
    print(f"psycopg {psycopg.__version__}")
    do_connect()
    do_migrate()
    do_types()
    print(f"\n{'=' * 60}")
    print(f"==== 实验 06 · pg_migration 全部 {PASS_COUNT} 项断言通过 [PASS] ====")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except AssertionError:
        print("\n==== 存在断言失败, 退出码 1 ====")
        sys.exit(1)
